Models/Target.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HRMS.Models
{
    public class Target
    {
        [Key]
        public int id { get; set; }
        public double? mvoh { get; set; }
        public double? lvoh { get; set; }
        public double? mvug { get; set; }
        public double? lvug { get; set; }
        public double? transformer { get; set; }
        public double? pole { get; set; }
        public double? meter { get; set; }
        public double? distribution_box { get; set; }
        public double? rmu { get; set; }
        public double? switchh { get; set; }
        public int? active { get; set; }
        public int? created_by { get; set; }
        public int? updated_by { get; set; }
        public int? deleted_by { get; set; }
        public DateTime? created_at { get; set; }
        public DateTime? updated_at { get; set; }
        public DateTime? deleted_at { get; set; }
    }
}

ViewModels/TargetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HRMS.ViewModels
{
    public class TargetViewModel
    {
        public int id { get; set; }
        public double? mvoh { get; set; }
        public double? lvoh { get; set; }
        public double? mvug { get; set; }
        public double? lvug { get; set; }
        public double? transformer { get; set; }
        public double? pole { get; set; }
        public double? meter { get; set; }
        public double? distribution_box { get; set; }
        public double? rmu { get; set; }
        public double? switchh { get; set; }
        public int? active { get; set; }
        public int? created_by { get; set; }
        public int? updated_by { get; set; }
        public int? deleted_by { get; set; }
        public DateTime? created_at { get; set; }
        public DateTime? updated_at { get; set; }
        public DateTime? deleted_at { get; set; }
    }
}

Controllers/TargetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRMS.Models;
using HRMS.ViewModels;
using HRMS.Auth;
using HRMS.Helpers;
using HRMS.Enums;

namespace HRMS.Controllers
{
    [CustomAuthenticationFilter]
    public class TargetController : BaseController
    {
        HRMSDBContext db = new HRMSDBContext();
        // GET: ProjectType
        public ActionResult Index()
        {
            if (!isA.SuperAdmin())
                return RedirectToAction("Index", "Dashboard");
            if (Request.IsAjaxRequest())
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                // Getting all data    
                var targetData = (from target in db.Targets
                                        select new TargetViewModel
                                        {
                                            id = target.id,
                                            mvoh = target.mvoh,
                                            lvoh = target.lvoh,
                                            mvug = target.mvug,
                                            lvug = target.lvug,
                                            active = target.active,
                                            created_at = target.created_at
                                        }).Where(n => n.active == (int)RowStatus.ACTIVE);

                //Search    
                if (!string.IsNullOrEmpty(searchValue))
                {
                    targetData = targetData.Where(
                        m => m.mvoh.ToString().ToLower().Contains(searchValue.ToLower()) 
                    || m.lvoh.ToString().ToLower().Contains(searchValue.ToLower()) 
                    || m.mvug.ToString().ToLower().Contains(searchValue.ToLower()) 
                    || m.lvug.ToString().ToLower().Contains(searchValue.ToLower()) 
                    || m.id.ToString().ToLower().Contains(searchValue.ToLower())
                    );
                }

                //total number of rows count     
                var displayResult = targetData.OrderByDescending(u => u.id).Skip(skip)
                     .Take(pageSize).ToList();
                var totalRecords = targetData.Count();

                return Json(new
                {
                    draw = draw,
                    recordsTotal = totalRecords,
                    recordsFiltered = totalRecords,
                    data = displayResult

                }, JsonRequestBehavior.AllowGet);

            }
            ViewBag.showAddTarget = db.Targets.Where(t=>t.active == (int)RowStatus.ACTIVE).ToList().Count();
            return View();
        }
        [HttpPost]
        public JsonResult saveTarget(TargetViewModel targetViewModel)
        {

            if (targetViewModel.id == 0)
            {
                Target target = AutoMapper.Mapper.Map<TargetViewModel, Target>(targetViewModel);

                target.created_at = DateTime.Now;
                target.created_by = Session["id"].ToString().ToInt();

                db.Targets.Add(target);
                db.SaveChanges();
            }
            else
            {

                Target oldTarget = db.Targets.Find(targetViewModel.id);

                oldTarget.mvoh = targetViewModel.mvoh;
                oldTarget.lvoh = targetViewModel.lvoh;
                oldTarget.mvug = targetViewModel.mvug;
                oldTarget.lvug = targetViewModel.lvug;
                oldTarget.active = targetViewModel.active;
                oldTarget.updated_by = Session["id"].ToString().ToInt();
                oldTarget.updated_at = DateTime.Now;

                db.SaveChanges();
            }

            return Json(new { message = "done" }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public JsonResult deleteTarget(int id)
        {
            Target deleteTarget = db.Targets.Find(id);
            deleteTarget.active = (int)RowStatus.INACTIVE;
            deleteTarget.deleted_by = Session["id"].ToString().ToInt();
            deleteTarget.deleted_at = DateTime.Now;
            db.SaveChanges();

            return Json(new { message = "done" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Target/Index.cshtml
@{
    ViewBag.Title = "Project Types";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="modal fade" id="manage_target_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <form action="" method="post" enctype='multipart/form-data'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal_title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-body">
                        <div class="form-row">
                            <input type="hidden" name="id" id="id" value="0" />
                            <div class="form-group col-md-6">
                                <label>MVOH</label>
                                <input name="mvoh" id="mvoh" type="number" step=".01" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-6">
                                <label>LVOH</label>
                                <input name="lvoh" id="lvoh" type="number" step=".01" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-6">
                                <label>MVUG</label>
                                <input name="mvug" id="mvug" type="number" step=".01" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-6">
                                <label>LVUG</label>
                                <input name="lvug" id="lvug" type="number" step=".01" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-12">
                                <label>Status</label>
                                <select class="form-control" name="active" id="active">
                                    <option value="1">Active</option>
                                    <option value="2">Inactive</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </form>
</div>


<div class="row">
    <div class="form-group col-4">
        <input class="form-control" type="text" id="text_search" name="text_search" placeholder="Search">
    </div>
    <div class="form-group col-2">
        <button id="search" class="btn btn-primary px-3 radius-30">Search</button>
    </div>
    <div class="form-group col-2">
        <button id="reset" class="btn btn-danger px-3 radius-30">Reset</button>
    </div>

</div>

<div class="card">
    <div class="card-header" id="productivity_target_card_header">
        @if (ViewBag.showAddTarget == 0)
        {
            <a href="javascript:void(0)" id="add_target"><i class="fa fa-plus"></i> Add Target</a>
        }
        else
        {
        <span>Productivty Targets</span>
        }
    </div>
    <div class="card-body">

        <div class="table-responsive">
            <table id="targetTable" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>MVOH</th>
                        <th>LVOH</th>
                        <th>MVUG</th>
                        <th>LVUG</th>
                        <th>Active</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>

            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script>
       $(document).ready(function () {

           var datatable = $('#targetTable')
               .DataTable({/* we added this from the other system to have same search and same pagination*/
                   "dom": "<'dt--top-section '<'row'<'col-sm-12 col-md-6 d-flex justify-content-md-start justify-content-center'B><'col-sm-12 col-md-6 d-flex justify-content-md-end justify-content-center mt-md-0 mt-3'f>>>" +
                       "<'table-responsive  'tr>" +
                       "<'dt--bottom-section d-sm-flex justify-content-sm-between text-center'<'dt--pages-count  mb-sm-0 mb-3'i><'dt--pagination'p>>",
                   "buttons": {
                       buttons: [
                           { extend: 'copy', className: 'btn btn-sm' },
                           { extend: 'csv', className: 'btn btn-sm' },
                           { extend: 'excel', className: 'btn btn-sm' },
                           { extend: 'print', className: 'btn btn-sm' }
                       ]
                   },
                   "oLanguage": {
                       "oPaginate": { "sPrevious": 'Perivous', "sNext": 'Next' },
                       "sInfo": "Showing page _PAGE_ of _PAGES_",
                       "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                       "sSearchPlaceholder": "Search...",
                       "sLengthMenu": "Results :  _MENU_",
                   },
                    "processing": true,
                    "serverSide": true,
                    "scrollX": true,
                    "stateSave": false,
                    "lengthChange": false,
                    "dom": 'Bfrtip',

                    "buttons": ['copy', 'excel', 'pdf', 'print'],
                    "pageLength":10,
                    "rowId": 'id',
                    "ajax": {
                        "url": "@Url.Action("Index", "Target")",
                        "type": "POST",
                        "datatype": "json",
                        "dataSrc": "data"
                    },
                    "columns": [
                        {
                            "data": "id",
                            "searchable": true
                        },
                        {
                            "data": "mvoh",
                            "searchable": true
                        },
                        {
                            "data": "lvoh",
                            "searchable": true
                        },
                        {
                            "data": "mvug",
                            "searchable": true
                        },
                        {
                            "data": "lvug",
                            "searchable": true
                        },
                        {
                            "data": "active", "searchable": true,
                            fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                                var html = "";
                                if (oData.active == 1)
                                    html += "<span class='badge badge-primary'>Active</span>";
                                else
                                    html += "<span class='badge badge-danger'>Active</span>";
                                $(nTd).html("<span class='action-column'>" + html + "</span>");
                            }
                        },
                        {
                            "data": "active", "searchable": true,
                            fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                                $(nTd).html("<span class='action-column'>" + fixDate(oData.created_at) + "</span>");
                            }
                        },
                        {
                            "data": "id", "searchable": true,
                            fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                                var html = "";

                                html += "<a class='edit' href='javascript:void(0)' title='Edit'><i class='far fa-edit'></i></a>&nbsp;";
                                //html += "<a class='delete' href='javascript:void(0)' title='Delete'><i class='fas fa-trash'></i></a>";
                                $(nTd).html("<span class='action-column'>" + html + "</span>");
                            }
                        },
                    ]
                 });

            $('#search').on('click', function () {
                datatable.search($("#text_search").val());
                datatable.draw();
            });

            $('#text_search').on('keyup', function (e) {
                if (e.keyCode == 13)
                    $('#search_button').trigger('click');
            });

            $('#reset').on('click', function () {
                $("#text_search").val("");

                $('#search').trigger('click');

            });

           $("#add_target").click(function () {
               var modal = $('#manage_target_modal').clone();
               var action = '@Url.Action("saveTarget", "Target")';
               modal.find('form').attr('action', action);
               modal.find('#modal_title').text('Add Target');
                modal.execModal({
                    progressBar: 'progress_bar',
                    progressText: 'progress_text',
                }, function (response) {

                        datatable.draw();
                        $("#productivity_target_card_header").empty();
                        $("#productivity_target_card_header").append(`<span>Productivty Targets</span>`);


                }, function (response) {

                }, function (dialog) {


                });
            });

            $(document).on("click", ".edit", function () {
                var data = datatable.row($(this).closest('tr')).data();
                console.log(data);
                var modal = $('#manage_target_modal').clone();
                var action = '@Url.Action("saveTarget", "Target")';
                modal.find('form').attr('action', action);
                modal.find('#modal_title').text('Edit Target');
                modal.execModal({
                    progressBar: 'progress_bar',
                    progressText: 'progress_text',
                }, function (response) {
                        datatable.draw();

                }, function (response) {

                }, function (dialog) {

                        dialog.find('#id').val(data.id);
                        dialog.find('#mvoh').val(data.mvoh);
                        dialog.find('#lvoh').val(data.lvoh);
                        dialog.find('#mvug').val(data.mvug);
                        dialog.find('#lvug').val(data.lvug);
                        dialog.find('#active option[value=' + data.active + ']').attr('selected', 'selected');

                });

            });

            @*$(document).on("click", ".delete", function () {
                var data = datatable.row($(this).closest('tr')).data();
                warningBox("Are you sure you want to delete this Target ?", function () {
                    $.ajax({
                        type: "GET",
                        url: '@Url.Action("deleteTarget", "Target")',
                        contentType: "application/json; charset=utf-8",
                        data: { "id": data.id },
                        datatype: "json",
                        success: function (data) {
                            datatable.draw();
                            $("#productivity_target_card_header").empty();
                            $("#productivity_target_card_header").append(`<a href="javascript:void(0)" id="add_target"><i class="fa fa-plus"></i> Add Target</a>`);
                        },
                        error: function () {
                            alert("Dynamic content load failed.");
                        }
                    });
                });
            });*@

        });

    </script>
}