Models/Asset.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HRMS.Models
{
    public class Asset
    {
        [Key]
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string notes { get; set; }
        public int? active { get; set; }

        [ForeignKey("User")]
        public int? created_by { get; set; }
        public User User { get; set; }
        public int? updated_by { get; set; }
        public int? deleted_by { get; set; }
        public DateTime? created_at { get; set; }
        public DateTime? updated_at { get; set; }
        public DateTime? deleted_at { get; set; }
    }
}

ViewModels/AssetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HRMS.ViewModels
{
    public class AssetViewModel
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string notes { get; set; }
        public int? branch_id { get; set; }
        public int? active { get; set; }
        public int? created_by { get; set; }
        public int? updated_by { get; set; }
        public int? deleted_by { get; set; }
        public DateTime? created_at { get; set; }
        public DateTime? updated_at { get; set; }
        public DateTime? deleted_at { get; set; }
    }
}

Controllers/AssetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRMS.Models;
using HRMS.ViewModels;
using HRMS.Auth;
using HRMS.Helpers;
using HRMS.Enums;

namespace HRMS.Controllers
{
    [CustomAuthenticationFilter]
    public class AssetController : BaseController
    {
        HRMSDBContext db = new HRMSDBContext();
        // GET: ProjectType
        public ActionResult Index(int? branch_id)
        {
            User currentUser = Session["user"] as User;
            if (!(isA.SuperAdmin()
                || (isA.BranchAdmin() && (currentUser.branch_id == branch_id || branch_id == null))
                ))
                return RedirectToAction("Index", "Dashboard");
            if (Request.IsAjaxRequest())
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                // Getting all data    
                var assetsData = (from asset in db.Assets
                                  join user in db.Users on asset.created_by equals user.id
                                  select new AssetViewModel
                                  {
                                      id = asset.id,
                                      name = asset.name,
                                      code = asset.code,
                                      notes = asset.notes,
                                      branch_id = user.branch_id,
                                      active = asset.active,
                                      created_at = asset.created_at
                                  }).Where(n => n.active == (int)RowStatus.ACTIVE);

                //Search    
                if (!string.IsNullOrEmpty(searchValue))
                {
                    assetsData = assetsData.Where(m => m.name.ToLower().Contains(searchValue.ToLower())
                    || m.id.ToString().ToLower().Contains(searchValue.ToLower())
                    || m.code.ToString().ToLower().Contains(searchValue.ToLower())
                    || m.notes.ToString().ToLower().Contains(searchValue.ToLower())
                    );
                }

                if(isA.SuperAdmin())
                {
                    if(branch_id != null)
                    {
                        assetsData = assetsData.Where(a => a.branch_id == branch_id);
                    }
                }

                if (isA.BranchAdmin())
                {
                    assetsData = assetsData.Where(a => a.branch_id == currentUser.branch_id);
               
                }
                //total number of rows count     
                var displayResult = assetsData.OrderByDescending(u => u.id).Skip(skip)
                     .Take(pageSize).ToList();
                var totalRecords = assetsData.Count();

                return Json(new
                {
                    draw = draw,
                    recordsTotal = totalRecords,
                    recordsFiltered = totalRecords,
                    data = displayResult

                }, JsonRequestBehavior.AllowGet);

            }
            if (isA.BranchAdmin())
                ViewBag.branch_id = currentUser.branch_id;
            else
                ViewBag.branch_id = branch_id;

            if (branch_id != null)
                ViewBag.branch_name = db.Branches.Find(branch_id).name;
            else
                ViewBag.branch_name = "Company";

            return View();
        }
        [HttpPost]
        public JsonResult saveAsset(AssetViewModel assetViewModel)
        {

            if (assetViewModel.id == 0)
            {
                Asset asset = AutoMapper.Mapper.Map<AssetViewModel, Asset>(assetViewModel);

                asset.active = (int)RowStatus.ACTIVE;
                asset.created_at = DateTime.Now;;
                asset.created_by = Session["id"].ToString().ToInt();

                db.Assets.Add(asset);
                db.SaveChanges();
            }
            else
            {

                Asset oldAsset = db.Assets.Find(assetViewModel.id);

                oldAsset.name = assetViewModel.name;
                oldAsset.code = assetViewModel.code;
                oldAsset.notes = assetViewModel.notes;
                oldAsset.active = assetViewModel.active;
                oldAsset.updated_by = Session["id"].ToString().ToInt();
                oldAsset.updated_at = DateTime.Now;;

                db.SaveChanges();
            }

            return Json(new { message = "done" }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public JsonResult deleteAsset(int id)
        {
            Asset deleteAsset = db.Assets.Find(id);
            deleteAsset.active = (int)RowStatus.INACTIVE;
            deleteAsset.deleted_by = Session["id"].ToString().ToInt();
            deleteAsset.deleted_at = DateTime.Now;;
            db.SaveChanges();

            return Json(new { message = "done" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Asset/Index.cshtml
@{
    ViewBag.Title = "Assets";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="modal fade" id="manage_asset_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <form action="" method="post" enctype='multipart/form-data'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal_title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-body">
                        <div class="form-row">
                            <input type="hidden" name="id" id="id" value="0" />
                            <div class="form-group col-md-12">
                                <label>Code</label>
                                <input name="code" id="code" type="text" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-12">
                                <label>Name</label>
                                <input required name="name" id="name" type="text" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-12">
                                <label>Notes</label>
                                <input name="notes" id="notes" type="text" class="form-control radius-30" />
                            </div>
                            <div class="form-group col-md-12">
                                <label>Status</label>
                                <select class="form-control" name="active" id="active">
                                    <option value="1">Active</option>
                                    <option value="2">Inactive</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="page-header">
    <nav class="breadcrumb-one" aria-label="breadcrumb">
        <ol class="breadcrumb">
            @if ((ViewBag.branch_id != null && HRMS.Auth.isA.SuperAdmin()) || HRMS.Auth.isA.BranchAdmin())
            {
                <li class="breadcrumb-item"><a href="@Url.Action("Show","Branch")">Branches</a></li>
                <li class="breadcrumb-item"><a href="@Url.Action("Details","Branch",new { id = ViewBag.branch_id})">@ViewBag.branch_name</a></li>
            }
            else if (ViewBag.branch_id == null && HRMS.Auth.isA.SuperAdmin())
            {
                <li class="breadcrumb-item"><a href="@Url.Action("Index","Dashboard")"><i class="fa fa-home"></i></a></li>
            }
            <li class="breadcrumb-item active" aria-current="page" style="font-weight:bold;">Assets</li>

        </ol>
    </nav>
</div>
<div class="row">
    <div class="form-group col-4">
        <input class="form-control" type="text" id="text_search" name="text_search" placeholder="Search">
    </div>
    <div class="form-group col-2">
        <button id="search" class="btn btn-primary px-3 radius-30">Search</button>
    </div>
    <div class="form-group col-2">
        <button id="reset" class="btn btn-danger px-3 radius-30">Reset</button>
    </div>

</div>

<div class="card">
    <div class="card-header">
        @if(HRMS.Auth.isA.BranchAdmin())
        {
            <a href="javascript:void(0)" id="add_asset"><i class="fa fa-plus"></i> Add Asset</a>
        }
        else
        { 
            <span>@ViewBag.branch_name Assets</span>
        }
    </div>
    <div class="card-body">

        <div class="table-responsive">
            <table id="assetsTable" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Code</th>
                        <th>Name</th>
                        <th>Notes</th>
                        <th>Active</th>
                        <th></th>
                    </tr>
                </thead>

            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script>
       $(document).ready(function () {

           var datatable = $('#assetsTable')
               .DataTable({/* we added this from the other system to have same search and same pagination*/
                   "dom": "<'dt--top-section '<'row'<'col-sm-12 col-md-6 d-flex justify-content-md-start justify-content-center'B><'col-sm-12 col-md-6 d-flex justify-content-md-end justify-content-center mt-md-0 mt-3'f>>>" +
                       "<'table-responsive  'tr>" +
                       "<'dt--bottom-section d-sm-flex justify-content-sm-between text-center'<'dt--pages-count  mb-sm-0 mb-3'i><'dt--pagination'p>>",
                   "buttons": {
                       buttons: [
                           { extend: 'copy', className: 'btn btn-sm' },
                           { extend: 'csv', className: 'btn btn-sm' },
                           { extend: 'excel', className: 'btn btn-sm' },
                           { extend: 'print', className: 'btn btn-sm' }
                       ]
                   },
                   "oLanguage": {
                       "oPaginate": { "sPrevious": 'Perivous', "sNext": 'Next' },
                       "sInfo": "Showing page _PAGE_ of _PAGES_",
                       "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                       "sSearchPlaceholder": "Search...",
                       "sLengthMenu": "Results :  _MENU_",
                   },
                    "processing": true,
                    "serverSide": true,
                    "scrollX": true,
                    "stateSave": false,
                    "lengthChange": false,
                    "dom": 'Bfrtip',

                    "buttons": ['copy', 'excel', 'pdf', 'print'],
                    "pageLength":10,
                    "rowId": 'id',
                    "ajax": {
                        "url": "@Url.Action("Index", "Asset")?branch_id=@ViewBag.branch_id",
                        "type": "POST",
                        "datatype": "json",
                        "dataSrc": "data"
                    },
                    "columns": [
                        {
                            "data": "id",
                            "searchable": true
                        },
                        {
                            "data": "code",
                            "searchable": true
                        },
                        {
                            "data": "name",
                            "searchable": true
                        },
                        {
                            "data": "notes",
                            "searchable": true
                        },
                        {
                            "data": "active", "searchable": true,
                            fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                                var html = "";
                                if (oData.active == 1)
                                    html += "<span class='badge badge-primary'>Active</span>";
                                else
                                    html += "<span class='badge badge-danger'>Active</span>";
                                $(nTd).html("<span class='action-column'>" + html + "</span>");
                            }
                        },
                        {
                            "data": "id", "searchable": true,
                            fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                                var html = "";
                                var isBranchAdmin = '@HRMS.Auth.isA.BranchAdmin()';
                                if (isBranchAdmin == 'True') {
                                    html += "<a class='edit' href='javascript:void(0)' title='Edit'><i class='far fa-edit'></i></a>&nbsp;";
                                    html += "<a class='delete' href='javascript:void(0)' title='Delete'><i class='fas fa-trash'></i></a>";
                                }
                                $(nTd).html("<span class='action-column'>" + html + "</span>");
                            }
                        },
                    ]
                 });

            $('#search').on('click', function () {
                datatable.search($("#text_search").val());
                datatable.draw();
            });

            $('#text_search').on('keyup', function (e) {
                if (e.keyCode == 13)
                    $('#search_button').trigger('click');
            });

            $('#reset').on('click', function () {
                $("#text_search").val("");

                $('#search').trigger('click');

            });

           $("#add_asset").click(function () {
               var modal = $('#manage_asset_modal').clone();
                var action = '@Url.Action("saveAsset", "Asset")';
                modal.find('form').attr('action', action);
               modal.find('#modal_title').text('Add Asset');
                modal.execModal({
                    progressBar: 'progress_bar',
                    progressText: 'progress_text',
                }, function (response) {

                        datatable.draw();

                }, function (response) {

                }, function (dialog) {


                });
            });

            $(document).on("click", ".edit", function () {
                var data = datatable.row($(this).closest('tr')).data();
                console.log(data);
                var modal = $('#manage_asset_modal').clone();
                var action = '@Url.Action("saveAsset", "Asset")';
                modal.find('form').attr('action', action);
                modal.find('#modal_title').text('Edit Asset');
                modal.execModal({
                    progressBar: 'progress_bar',
                    progressText: 'progress_text',
                }, function (response) {
                        datatable.draw();

                }, function (response) {

                }, function (dialog) {

                        dialog.find('#id').val(data.id);
                        dialog.find('#code').val(data.code);
                        dialog.find('#name').val(data.name);
                        dialog.find('#notes').val(data.notes);
                        dialog.find('#active option[value=' + data.active + ']').attr('selected', 'selected');

                });

            });

            $(document).on("click", ".delete", function () {
                var data = datatable.row($(this).closest('tr')).data();
                warningBox("Are you sure you want to delete this Project Type (<b>" + data.name +"</b>) ?", function () {
                    $.ajax({
                        type: "GET",
                        url: '@Url.Action("deleteAsset", "Asset")',
                        contentType: "application/json; charset=utf-8",
                        data: { "id": data.id },
                        datatype: "json",
                        success: function (data) {
                            datatable.draw();
                        },
                        error: function () {
                            alert("Dynamic content load failed.");
                        }
                    });
                });
            });

        });

    </script>
}